"""remove unique constraint from isbn

Revision ID: c0b46fe85273
Revises: 79ff9e25126d
Create Date: 2025-06-23 10:13:56.751407

"""
from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0b46fe85273"
down_revision: Union[str, None] = "79ff9e25126d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("isbn", "book", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("isbn", "book", ["isbn"])
    # ### end Alembic commands ###
