"""add publisher table and relation

Revision ID: 78caaf37453d
Revises: d80acdf23c07
Create Date: 2025-12-05 13:41:47.632545

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from app.enums import Status

# revision identifiers, used by Alembic.
revision: str = "78caaf37453d"
down_revision: Union[str, None] = "d80acdf23c07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publisher",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("status", sa.Enum(Status), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("book", sa.Column("publisher_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_book_publisher", "book", "publisher", ["publisher_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_book_publisher", "book", type_="foreignkey")
    op.drop_column("book", "publisher_id")
    op.drop_table("publisher")
    # ### end Alembic commands ###
