"""add panel user login history

Revision ID: a96062d82b60
Revises: c0b46fe85273
Create Date: 2025-11-09 13:26:32.803510

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a96062d82b60"
down_revision: Union[str, None] = "c0b46fe85273"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_user_login_history",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("admin_user_id", sa.Integer, sa.ForeignKey("admin_user.id"), nullable=False),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="active"),
        sa.Column("date_created", sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column("date_modified", sa.DateTime, nullable=False, server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_user_login_history")
    # ### end Alembic commands ###
