"""initial_migration

Revision ID: 79ff9e25126d
Revises:
Create Date: 2025-05-30 14:08:41.112014

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from app.enums import Status

# revision identifiers, used by Alembic.
revision: str = "79ff9e25126d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=200), nullable=True),
        sa.Column("status", sa.Enum(Status), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("status", sa.Enum(Status), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "panel_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("phone_number", sa.String(length=15), nullable=False),
        sa.Column("password_hash", sa.String(length=120), nullable=False),
        sa.Column("status", sa.Enum(Status), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("phone_number", sa.String(length=15), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("email_verification", sa.Boolean(), nullable=False),
        sa.Column("phone_verification", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(length=120), nullable=False),
        sa.Column("status", sa.Enum(Status), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("isbn", sa.String(length=20), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("published_year", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("barcode", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum(Status), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["author.id"], name="fk_book_author"),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], name="fk_book_category"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isbn"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book")
    op.drop_table("user")
    op.drop_table("panel_user")
    op.drop_table("category")
    op.drop_table("author")
    # ### end Alembic commands ###
