books = [
    {
        "title": "Benim Adım Kırmızı",
        "isbn": "9789753425986",
        "author_id": 1,
        "category_id": 1,
        "publisher_id": 1,
        "published_year": 1998,
        "page_count": 464,
        "barcode": 1000001,
        "description": "Osmanlı döneminde geçen tarihi bir roman.",
        "status": "active",
    },
    {
        "title": "Bir Ömür Nasıl Yaşanır?",
        "isbn": "9789752430990",
        "author_id": 2,
        "category_id": 3,
        "publisher_id": 2,
        "published_year": 2019,
        "page_count": 288,
        "barcode": 1000002,
        "description": "Galaktik imparatorluk çökerken bilimin rolü.",
        "status": "active",
    },
    {
        "title": "Sefiller",
        "isbn": "9786054977840",
        "author_id": 3,
        "category_id": 1,
        "publisher_id": 3,
        "published_year": 1862,
        "page_count": 1724,
        "barcode": 1000003,
        "description": "Adalet ve merhamet temasını derin şekilde işleyen klasik bir roman.",
        "status": "active",
    },
    {
        "title": "Masumiyet Müzesi",
        "isbn": "9789750829444",
        "author_id": 1,
        "category_id": 1,
        "publisher_id": 1,
        "published_year": 2008,
        "page_count": 592,
        "barcode": 1000004,
        "description": "Tutkulu ve takıntılı bir aşkın izini süren bir roman.",
        "status": "active",
    },
    {
        "title": "Hayvan Çiftliği",
        "isbn": "9789750719387",
        "author_id": 4,
        "category_id": 5,
        "publisher_id": 4,
        "published_year": 1945,
        "page_count": 152,
        "barcode": 1000005,
        "description": "Totaliter rejimlerin eleştirisini yapan alegorik bir eser.",
        "status": "active",
    },
    {
        "title": "Dune",
        "isbn": "9786053754787",
        "author_id": 5,
        "category_id": 2,
        "publisher_id": 2,
        "published_year": 1965,
        "page_count": 688,
        "barcode": 1000007,
        "description": "Çöl gezegeni Arrakis’te geçen epik bir bilim kurgu hikâyesi.",
        "status": "active",
    },
    {
        "title": "Simyacı",
        "isbn": "9789750726431",
        "author_id": 6,
        "category_id": 3,
        "publisher_id": 4,
        "published_year": 1988,
        "page_count": 188,
        "barcode": 1000008,
        "description": "Kişisel yolculuğun anlamını arayan sembolik bir roman.",
        "status": "active",
    },
]
