books = [
    {
        "title": "Benim Adım Kırmızı",
        "isbn": "9789753425986",
        "author_id": 1,
        "category_id": 1,
        "published_year": 1998,
        "page_count": 464,
        "barcode": 1000001,
        "description": "Osmanlı döneminde geçen tarihi bir roman.",
        "status": "active",
    },
    {
        "title": "Vakıf",
        "isbn": "9780553293357",
        "author_id": 2,
        "category_id": 2,
        "published_year": 1951,
        "page_count": 255,
        "barcode": 1000002,
        "description": "Galaktik imparatorluk çökerken bilimin rolü.",
        "status": "active",
    },
    {
        "title": "Tarih Boyunca Dünya",
        "isbn": None,
        "author_id": 2,
        "category_id": 3,
        "published_year": 1990,
        "page_count": 300,
        "barcode": 1000003,
        "description": "Kapsamlı bir tarih özeti.",
        "status": "passive",
    },
]
